import json
import pathlib
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
  sys.path.insert(0, str(ROOT))

DEFAULT_REGRESSION_REPEATS = 2

def pytest_addoption(parser):
  parser.addoption(
    "--regression-repeats",
    action="store",
    default=DEFAULT_REGRESSION_REPEATS,
    type=int,
    help="Random coef draws per vectorized regression test (default: %(default)s)",
  )

def pytest_configure(config):
  nb = json.loads((ROOT / "add_sync.ipynb").read_text())

  cells_to_export = [
    cell for cell in nb["cells"]
    if "export" in cell.get("metadata", {}).get("tags", [])
  ]

  lines = ["".join(cell["source"]) for cell in cells_to_export]

  (ROOT / "add_sync_export.py").write_text(
    f"# add_sync_export.py\n# this file was generated by conftest.py\n\n" + "\n\n".join(lines)
  )

@pytest.fixture
def regression_repeats(request):
  return request.config.getoption("--regression-repeats")
